### ISSUE TITLE
The plugin is too large, what is the optimization method? Can it be integrated on demand?

### ISSUE THREAD

**Issue by OHeroJ** [AgoraIO-Extensions/Agora-Flutter-SDK#688]
插件体积过于庞大，有何优化手段？能否按需集成

**Comment by maxxfrazer** [comment]
Can you see which files are too large for your environment? Is it files included in previous commits on this repo?

**Comment by OHeroJ** [comment]
> Can you see which files are too large for your environment? Is it files included in previous commits on this repo?

![8861653351979pic](https://user-images.githubusercontent.com/12316547/169924889-c643cd5e-9cdb-461c-a399-9ad00c504cf9.jpg)

**Comment by maxxfrazer** [comment]
that what i thought, i saw before that these framework files were uploaded to previous commits from a long time ago.
@littleGnAl the repo is, i believe, over 300mb because of these mistakenly uploaded frameworks. would expect it shouldn't be more than 10mb.

could you look at stripping the large files out? i'm happy to do it if you're not able to right now, all people with clones will need to pull a forced update though, to avoid re-pushing the files

**Comment by littleGnAl** [comment]
@maxxfrazer This is not that issue.

**Comment by littleGnAl** [comment]
Please check https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1214
